# -*- coding: utf-8 -*-
"""predictions

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GHoqGYmYU1hkorCGNlBGfntMSVcg_Hrb
"""

import torch.nn.functional as F

def predict_toxicity(text_input):
    encoded_input = tokenizer(
        text_input,
        padding=True,
        truncation=True,
        max_length=150,
        return_tensors='pt'
    )

    input_ids = encoded_input['input_ids'].to(device)
    attention_mask = encoded_input['attention_mask'].to(device)

    model.eval()

    with torch.no_grad():
        logits = model(input_ids, attention_mask)

    probabilities = F.sigmoid(logits)

    return probabilities.cpu().numpy().flatten()
